import type { IDesignTokens } from "../types";

// Each value names its own token and scheme so the generated CSS shows exactly which value landed where.
export const fixture_designTokens: IDesignTokens = {
  schemes: {
    dark: {
      surface: "dark-surface",
      surface2: "dark-surface2",
      surface3: "dark-surface3",
      fg: "dark-fg",
      fgMuted: "dark-fgMuted",
      fgFaint: "dark-fgFaint",
      line: "dark-line",
      edge: "dark-edge",
      halo: "dark-halo",
      shadow: "dark-shadow",
      accent: "dark-accent",
      onAccent: "dark-onAccent",
      ok: "dark-ok",
      onOk: "dark-onOk",
      warn: "dark-warn",
      onWarn: "dark-onWarn",
      danger: "dark-danger",
      onDanger: "dark-onDanger",
      dangerSoft: "dark-dangerSoft",
      backdrop: "dark-backdrop",
      termBg: "dark-termBg",
    },
    light: {
      surface: "light-surface",
      surface2: "light-surface2",
      surface3: "light-surface3",
      fg: "light-fg",
      fgMuted: "light-fgMuted",
      fgFaint: "light-fgFaint",
      line: "light-line",
      edge: "light-edge",
      halo: "light-halo",
      shadow: "light-shadow",
      accent: "light-accent",
      onAccent: "light-onAccent",
      ok: "light-ok",
      onOk: "light-onOk",
      warn: "light-warn",
      onWarn: "light-onWarn",
      danger: "light-danger",
      onDanger: "light-onDanger",
      dangerSoft: "light-dangerSoft",
      backdrop: "light-backdrop",
      termBg: "light-termBg",
    },
  },
  marks: {
    mark: "mark",
    markInk: "markInk",
    markAlt: "markAlt",
    markHaloIn: "markHaloIn",
    markHaloOut: "markHaloOut",
  },
  shape: {
    radiusSm: "radiusSm",
    radiusMd: "radiusMd",
  },
};
