name = "devhost-www"

[devtools.editor]
enabled = true
ide = "neovim"

[devtools.minimap]
enabled = true
position = "right"

[devtools.status]
enabled = true
position = "top-right"

[services.devhost-www]
primary = true
command = "bun dev"
cwd = "."
port = 3200
host = "devhost.localhost"

[services.logs]
command = "bun log-demo"
cwd = "."
health = { process = true }
