name = "www"

[devtools.editor]
enabled = true
ide = "neovim"

[devtools.externalToolbars]
enabled = true

[devtools.minimap]
enabled = true
position = "right"

[devtools.status]
enabled = true
position = "top-right"

# [services.toolbar-test]
# command = "bun dev"
# cwd = "./skit"
# host = "test.localhost"

[services.devhost-www]
primary = true
command = "bun dev"
cwd = "."
port = 3200
host = "devhost.localhost"

[services.logs]
command = "bun log-demo"
cwd = "."
health = { process = true }
