name = "www"

[caddy.global]
bindHost = "0.0.0.0"
http = true

[devtools.editor]
enabled = true
ide = "neovim"

[devtools.externalToolbars]
enabled = true

[devtools.minimap]
enabled = true
position = "right"

[devtools.status]
enabled = true
position = "top-right"

[services.devhost-www]
primary = true
command = "bun dev"
cwd = "."
port = 3200
# host = "devhost.localhost"
host = "devhost-devbox.cvb.lol"

[services.logs]
command = "bun log-demo"
cwd = "."
health = { process = true }
