import type { ColorScheme, IDesignTokens, IMarkPalette, ISchemePalette, IShapeTokens, ITerminalPalette } from "./types";

export const DESIGN_TOKENS: IDesignTokens = {
  schemes: {
    dark: {
      surface: "#121417",
      surface2: "#1c1f24",
      surface3: "#282c33",
      fg: "#eceff3",
      fgMuted: "#a3abb6",
      fgFaint: "#6f7783",
      line: "#353b44",
      edge: "rgb(255 255 255 / 0.24)",
      halo: "rgb(0 0 0 / 0.92)",
      shadow: "0 6px 22px rgb(0 0 0 / 0.5)",
      accent: "#ff5cd6",
      onAccent: "#1a0014",
      ok: "#3ddc84",
      onOk: "#00210f",
      warn: "#ffb224",
      onWarn: "#231500",
      danger: "#ff6159",
      onDanger: "#1f0000",
      dangerSoft: "rgb(255 97 89 / 0.16)",
      backdrop: "rgb(4 5 7 / 0.7)",
      termBg: "#0b0c0f",
    },
    light: {
      surface: "#fcfcfd",
      surface2: "#eef0f3",
      surface3: "#e0e4ea",
      fg: "#0c0e11",
      fgMuted: "#4b535e",
      fgFaint: "#7c8490",
      line: "#c7ccd4",
      edge: "rgb(0 0 0 / 0.42)",
      halo: "rgb(255 255 255 / 0.95)",
      shadow: "0 6px 22px rgb(0 0 0 / 0.3)",
      accent: "#b8168c",
      onAccent: "#ffffff",
      ok: "#0a7d40",
      onOk: "#ffffff",
      warn: "#a35400",
      onWarn: "#ffffff",
      danger: "#cc1f1f",
      onDanger: "#ffffff",
      dangerSoft: "rgb(204 31 31 / 0.1)",
      backdrop: "rgb(10 12 16 / 0.55)",
      termBg: "#ffffff",
    },
  },
  marks: {
    mark: "#ff4fd8",
    markInk: "#000000",
    markAlt: "#1ee3ff",
    markHaloIn: "#ffffff",
    markHaloOut: "#000000",
  },
  shape: {
    radiusSm: "2px",
    radiusMd: "4px",
  },
};

export const TERMINAL_PALETTES: Record<ColorScheme, ITerminalPalette> = {
  dark: {
    background: "#0b0c0f",
    foreground: "#eceff3",
    cursor: "#ff5cd6",
    cursorAccent: "#0b0c0f",
    selectionBackground: "#353b44",
    black: "#1c1f24",
    red: "#ff6159",
    green: "#3ddc84",
    yellow: "#ffb224",
    blue: "#6cb6ff",
    magenta: "#ff5cd6",
    cyan: "#39d0e6",
    white: "#a3abb6",
    brightBlack: "#6f7783",
    brightRed: "#ff8a84",
    brightGreen: "#6ee7a8",
    brightYellow: "#ffd27a",
    brightBlue: "#96d0ff",
    brightMagenta: "#ff8ae2",
    brightCyan: "#7ee8fa",
    brightWhite: "#ffffff",
  },
  light: {
    background: "#ffffff",
    foreground: "#0c0e11",
    cursor: "#b8168c",
    cursorAccent: "#ffffff",
    selectionBackground: "#e0e4ea",
    black: "#0c0e11",
    red: "#cc1f1f",
    green: "#0a7d40",
    yellow: "#a35400",
    blue: "#0b5bd3",
    magenta: "#b8168c",
    cyan: "#087686",
    white: "#4b535e",
    brightBlack: "#4b535e",
    brightRed: "#e02d2d",
    brightGreen: "#0d8f4a",
    brightYellow: "#b86200",
    brightBlue: "#1f6feb",
    brightMagenta: "#c52aa0",
    brightCyan: "#0a8a9c",
    brightWhite: "#7c8490",
  },
};

// Custom property names are the public CSS contract of tokens.css; consumers reference them as `var(--dh-*)`.
export const SCHEME_TOKEN_NAMES: Record<keyof ISchemePalette, string> = {
  surface: "--dh-surface",
  surface2: "--dh-surface-2",
  surface3: "--dh-surface-3",
  fg: "--dh-fg",
  fgMuted: "--dh-fg-muted",
  fgFaint: "--dh-fg-faint",
  line: "--dh-line",
  edge: "--dh-edge",
  halo: "--dh-halo",
  shadow: "--dh-shadow",
  accent: "--dh-accent",
  onAccent: "--dh-on-accent",
  ok: "--dh-ok",
  onOk: "--dh-on-ok",
  warn: "--dh-warn",
  onWarn: "--dh-on-warn",
  danger: "--dh-danger",
  onDanger: "--dh-on-danger",
  dangerSoft: "--dh-danger-soft",
  backdrop: "--dh-backdrop",
  termBg: "--dh-term-bg",
};

export const MARK_TOKEN_NAMES: Record<keyof IMarkPalette, string> = {
  mark: "--dh-mark",
  markInk: "--dh-mark-ink",
  markAlt: "--dh-mark-alt",
  markHaloIn: "--dh-mark-halo-in",
  markHaloOut: "--dh-mark-halo-out",
};

export const SHAPE_TOKEN_NAMES: Record<keyof IShapeTokens, string> = {
  radiusSm: "--dh-radius-sm",
  radiusMd: "--dh-radius-md",
};
